- name: Ansible playbook to create all roboshop jobs
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    pipeline_jobs:
      - { jobName: "Sample3" folderName: "demo" repoName: "jenkins-learning"}
      - { jobName: "Sample4" folderName: "demo" repoName: "jenkins-somthing"}




