- name: create jenkins folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin
    user: admin
    url: http://172.31.8.47:8080
  loop:
    - demo

- name: create jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: "{{item.foldername}}/{{item.jobname}}"
    password: admin
    user: admin
    url: http://172.31.8.47:8080
  loop:
    - { jobname: "sample3", foldername: "demo"}
    - { jobname: "sample4", foldername: "demo"}