- name: create jenkins folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin
    user: admin
    url: http://172.31.8.47:8080
  loop:
    - demo

- name: create pipeline Jobs
  include_role:
    name: jenkins-jobs
    tasks_from: pipeline-job
  loop: "{{pipeline_jobs}}"




