- name: create jenkins job using basic authantication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline-jobs.xml') }}"
    name: admin
    password: admin
    url: http://172.31.8.47:8080
